### PR TITLE
Validator prune

### LINKED ISSUE #89: Validator messages pruning logic
~It should work like this:~

- [ ] drop Heartbeats that are older than a threshold 
- [ ] drop Accounting messages that are older than a threshold; can always be replayed via eventAggrs
- [ ] drop NewState/ApproveState older than a threshold, except ones with the stateRoot of the `lastApproved` (to ensure we can't drop our last approved pair)

**see below**

----------

after a few discussions with @samparsky, it would be sufficient to:

- [ ] drop Heartbeats that are older than threshold
- [ ] drop all validator messages for expired channels (`channel.validUntil`); this can be done via an additional prune script
- [ ] add a maximum channel validity that's accepted (ethereum adapter); should be 1 year

(re accounting messages: removing them is extremely dangerous, since if we remove the last available one, then everything is practically broken cause accounting will start from 0)

### PR DESCRIPTION
**Pull request by samparsky**
fixes #89 
- [x] drop Heartbeats that are older than threshold
- [x] drop all validator messages for expired channels (channel.validUntil); this can be done via an additional prune script
- [x] add a maximum channel validity that's accepted (ethereum adapter); should be 1 year

### CODE REVIEW

File: scripts/prune.js [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+			'msg.type': 'Heartbeat',
+			received: { $lte: new Date(timestamp) }
+		})
+	} else {
+		logger.info(`Deleting all validator messages for expired channel ${channelId}`)
+		await validatorCol.deleteMany({
+			channelId
+		})
+	}
+	logger.info(`Successfully pruned heartbeat messages for channel ${channelId}`)
```
Comment (Ivshti) [inline scripts/prune.js]: this message should be changed to "pruned messages for channel"

File: scripts/prune.js [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+}
+
+async function pruneAll() {
```
Comment (Ivshti) [inline scripts/prune.js]: rename to `pruneExpired`

File: scripts/prune.sh [hunk 3]
```diff
@@ -1,30 +1,30 @@
...
-# timestamp ( default= current date ) e.g. 2015-01-01
-# channel (required)
-# database (required) (default = adexValidator)
-# expired (optional) (values = true ) IMPORTANT: if set deletes all validator messages should be used for expired channelsonly
-# 
-# 
-# Example
-# 
-# Delete Heartbeat messages from a specific date
-# ./sccripts/prune.sh -database testValStackLeader1558782672 -timestamp 2012-01-01 -channel testing
```
Comment (Ivshti) [inline scripts/prune.sh]: typo: `sscripts`

File: scripts/prune.js [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+				await run()
+			}
+			process.exit()
+		})
+		.catch(err => {
+			logger.error(err.message)
+		})
+}
+
+async function run() {
```
Comment (Ivshti) [inline scripts/prune.js]: add an arguments `channelId` ad `timestamp` here, and rename to `pruneChannel`

then, we should have a new function `pruneAll` that will call `pruneExpired` (current `pruneAll`) and `pruneChannel` for each non-expired channel

File: test/run-integration-tests.sh [hunk 5]
```diff
@@ -65,7 +61,7 @@ else
 	echo -e "\033[0;31mTests failed: waiting 20s before cleaning the database (press ctrl-C to avoid cleanup)\033[0m"
 	echo "MongoDB database names: $LEAD_MONGO, $FOLLOW_MONGO"
 	(
-		sleep 20 &&
+		# sleep 20 &&
```
Comment (Ivshti) [inline test/run-integration-tests.sh]: revert this

File: test/run-integration-tests.sh [hunk 6]
```diff
@@ -43,7 +43,10 @@ else
 	# Ethereum local testnet
 	./test/scripts/ethereum.sh
 
-	./test/routes.js  && ./test/ethereum_adapter.js && ./test/integration.js && ./test/access.js
+	# Run integration & prune tests
+	./test/integration.js
```
Comment (Ivshti) [inline test/run-integration-tests.sh]: you missed this
